### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by dev-zero** [luckylittle/Manning-Publications-Ebooks-Downloader#4]
When trying the script, I get:

```
Created folder Manning_2021-12-27
Traceback (most recent call last):
  File "/home/user/bin/manning-publications-ebooks-downloader-venv/Manning-Publications-Ebooks-Downloader/./manning.py", line 138, in <module>
    get_list()
  File "/home/user/bin/manning-publications-ebooks-downloader-venv/Manning-Publications-Ebooks-Downloader/./manning.py", line 69, in get_list
    'lt': soup0.find('input', {'name': 'lt'}).get('value'),
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by dev-zero** [comment]
The `selenium` branch of @bdkech works :) ... also needed a tweak of the shebang, and I had to enable `headless` mode since I am running this on a remote host, but is downloading now.

**Comment by falaqm** [comment]
I have the same issue. I tried the selenium branch but it didn't work.and I got the same error. Could you please explain what all you changed?

**Comment by ilumin** [comment]
It's because `BeautifulSoup` cannot get the value of input name `lt` (I think it renders by JS), that's why it's undefined. After searching for more information, they suggested using Selenium to help soup get page data after JS was executed.
